name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  # Set your custom domain here, or leave empty to use root-relative URLs (/)
  # Root-relative URLs work with any domain (GitHub Pages or custom)
  # Example: BASE_URL: https://docs.example.com
  BASE_URL: ""

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docs with zola-builder
        uses: gabrielkoerich/zola-builder@main
        with:
          base-url: ${{ env.BASE_URL }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .zola-build/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
